-- Habilitar extensión de Postgres para encriptar contraseñas
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- 1. Tabla: Nodos del Bracket (Partidos, equipos y goles)
CREATE TABLE public.nodos_bracket (
    id_nodo TEXT PRIMARY KEY,
    nombre_equipo TEXT DEFAULT 'Por definir',
    goles TEXT DEFAULT '_',
    corazones INTEGER DEFAULT 0
);

-- 2. Tabla: Registro de Votos (Anti-spam por IP)
CREATE TABLE public.registro_votos (
    id_voto BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_nodo TEXT REFERENCES public.nodos_bracket(id_nodo) ON DELETE CASCADE,
    ip_usuario TEXT NOT NULL,
    creado_el TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    -- Regla de oro: Una misma IP no puede votar dos veces por el mismo nodo
    UNIQUE(id_nodo, ip_usuario)
);

-- 3. Tabla: Credenciales Admin
CREATE TABLE public.credenciales_admin (
    id_admin BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario TEXT UNIQUE NOT NULL,
    clave_hash TEXT NOT NULL
);

-- 4. Tabla: Estado del Torneo (Campeón actual)
CREATE TABLE public.estado_torneo (
    clave TEXT PRIMARY KEY,
    valor TEXT NOT NULL
);


-- ==========================================
-- DATOS INICIALES (SEMBRADO)
-- ==========================================

-- A) Crear tu usuario administrador con contraseña encriptada (Reemplaza 'TU_CONTRASEÑA' con tu contraseña real)
INSERT INTO public.credenciales_admin (usuario, clave_hash)
VALUES (
    'admin',
    crypt('TU_CONTRASEÑA', gen_salt('bf'))
) ON CONFLICT (usuario) DO NOTHING;

-- B) Crear el estado inicial del campeón
INSERT INTO public.estado_torneo (clave, valor)
VALUES ('champion_text_v2', 'return Campeón;') ON CONFLICT (clave) DO NOTHING;


-- ==========================================
-- FUNCIONES DE BASE DE DATOS (RPC)
-- ==========================================

-- Función para verificar de forma 100% segura la contraseña del administrador sin exponerla
CREATE OR REPLACE FUNCTION public.verificar_admin(p_usuario text, p_password text)
RETURNS boolean
SECURITY DEFINER -- Ejecuta con privilegios del creador para poder leer la tabla credenciales_admin
LANGUAGE plpgsql
AS $$
DECLARE
    v_hash text;
BEGIN
    -- Obtener la clave hash correspondiente al usuario
    SELECT clave_hash INTO v_hash FROM public.credenciales_admin WHERE usuario = p_usuario;
    
    IF v_hash IS NULL THEN
        RETURN false;
    END IF;
    
    -- Comparar la contraseña ingresada con el hash usando pgcrypto
    RETURN v_hash = crypt(p_password, v_hash);
END;
$$;


-- ==========================================
-- REALTIME SUBSCRIPTIONS
-- ==========================================

-- Habilitar la transmisión en tiempo real para las tablas clave
ALTER TABLE public.nodos_bracket REPLICA IDENTITY FULL;
ALTER TABLE public.registro_votos REPLICA IDENTITY FULL;

-- Agregar tablas a la publicación de Supabase Realtime
BEGIN;
  DROP PUBLICATION IF EXISTS supabase_realtime;
  CREATE PUBLICATION supabase_realtime FOR TABLE public.nodos_bracket, public.registro_votos;
COMMIT;

